//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectGCA3._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Chaves
    {
        public int ID_ChaveAtivacao { get; set; }
        public string NomeSoftware { get; set; }
        public string Fabricante { get; set; }
        public string TipoLicenca { get; set; }
        public string PrazoLicenca { get; set; }
        public string ChaveAtivacao { get; set; }
        public Nullable<int> ID_TipoLicenca { get; set; }
        public string Status { get; set; }
        public Nullable<int> Deleted { get; set; }
    }
}
