//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectGCA3._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Relacionamento
    {
        public int ID_UsuarioRelacionar { get; set; }
        public string Usuario { get; set; }
        public string Maquina { get; set; }
        public string ChaveAtivacao { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
        public Nullable<int> ID_Maquina { get; set; }
        public Nullable<int> ID_ChaveAtivacao { get; set; }
    }
}
